- name: Install F2FS tools
  apk:
    name: f2fs-tools
    state: present

- name: Add USBKEY in /etc/fstab
  mount:
    path: /media/USBKEY
    src: LABEL=USBKEY
    fstype: f2fs
    opts: noatime
    passno: 2
    state: mounted

- name: Install samba
  apk:
    name: samba-server
    state: present

- name: Enable samba
  service:
    name: samba
    enabled: yes
  notify: restart samba

- name: Copy smb.conf
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    mode: 0644
  notify: restart samba

- name: Enable Avahi service for Samba
  copy:
    src: smb.service
    dest: /etc/avahi/services/smb.service
    mode: 0644
  notify: restart avahi
