- name: Install mpc package
  apk: name=mpc state=present

- name: Copy mpd-starter init.d script
  template: src=mpd-starter.service dest=/etc/init.d/mpd-starter mode=0755

- name: Add mpd-starter init.d script to LBU included files
  command: lbu add -v /etc/init.d/mpd-starter
  register: lbucmd
  changed_when: '"Adding" in lbucmd.stdout'

- name: Enable mpd-starter
  service: name=mpd-starter enabled=yes
