- name: Create mpd root directory
  file: path="{{ mpd_rootdir }}" state=directory owner=mpd group=audio mode=0755   

- name: Create playlists and music directories
  file: path="{{ item }}" state=directory owner=mpd group=audio mode=0777
  loop:
    - "{{ mpd_rootdir }}/music"
    - "{{ mpd_rootdir }}/playlists"

- name: Check if file mpd.db already exists
  stat: path="{{ usbkey_mnt }}/mpd/mpd.db"
  register: mpddb

- name: Fix owner and rights on file mpd.db
  file: path="{{ usbkey_mnt }}/mpd/mpd.db" state=file owner=mpd group=audio mode=0644
  when: mpddb.stat.exists == true

- name: Copy /etc/mpd.conf
  template: src=mpd.conf dest=/etc/mpd.conf owner=mpd group=audio mode=0640
  notify: restart mpd

- name: Enable mpd
  service: name=mpd enabled=yes
