- name: Enable samba
  service: name=samba enabled=yes

- name: Copy smb.conf
  template: src=smb.conf dest=/etc/samba/smb.conf mode=0644
  notify: restart samba

- name: Disable startup of nmbd
  replace:
    path: /etc/conf.d/samba
    regexp: '^daemon_list="smbd nmbd"'
    replace: 'daemon_list="smbd"'
  notify: restart samba

- import_tasks: avahi.yml

- name: Enable Avahi service for Samba
  template: src=smb.service dest=/etc/avahi/services/smb.service mode=0644
  notify: restart avahi
