- name: Setting facts
  set_fact:
    hostname: "{{ hostname | default(ansible_hostname) }}"
    dac: "{{ dac | mandatory }}"
    radiogagad_enabled: "{{ radiogagad_enabled | default(true) | bool }}"
    usbkey_enabled: "{{ usbkey_enabled | default(true) | bool }}"
    usbkey_label: "{{ usbkey_label | default('') }}"
    usbkey_mnt: "{{ usbkey_mnt | default('') }}"
    mpd_rootdir: "/etc/mpd"
  tags: ["always"]

- name: Setting mpd root directory on usbkey
  set_fact:
    mpd_rootdir: "{{ usbkey_mnt }}/mpd"
  when: usbkey_enabled == true 
  tags: ["always"]

- name: Enable community APK repository
  replace:
    path: /etc/apk/repositories
    regexp: '^#(http://.*/v.*/community)'
    replace: '\1'
  tags: ['base']

- name: Install base packages
  apk:
    name: "{{ item }}"
    state: present
  loop:
    - raspberrypi
    - f2fs-tools
  tags: ['base']

- name: Disable useless services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - "crond"
  tags: ['base']

- name: Remove useless console getty
  lineinfile:
    path: /etc/inittab
    state: absent
    regexp: '^{{ item }}:.*getty.*' 
  loop:
    - "tty2"
    - "tty3"
    - "tty4"
    - "tty5"
    - "tty6"
  tags: ['base']

- name: Blacklist video related modules
  lineinfile:
    path: /etc/modprobe.d/radiogaga_blacklist.conf
    line: "{{ item }}"
    create: yes
  loop:
    - blacklist bcm2835_codec
    - blacklist bcm2835_v4l2
    - blacklist media
    - blacklist vc_sm_cma
  tags: ['base']

- name: Disable IPv4 Duplicate Address Detection
  file:
    path: /etc/network/if-up.d/dad
    mode: "a-x"
  tags: ['base']

- import_tasks: rngd.yml
  tags: ['base']

- import_tasks: syslog.yml
  tags: ['base']

- import_tasks: firmware.yml
  tags: ['base']

- import_tasks: mpd.yml
  tags: ['mpd']

- import_tasks: avahi.yml
  when: usbkey_enabled == true
  tags: ['mpd']

- import_tasks: usbkey.yml
  when: usbkey_enabled == true
  tags: ['mpd']

- import_tasks: samba.yml
  when: usbkey_enabled == true
  tags: ['mpd']

- import_tasks: noradiogagad.yml
  when: radiogagad_enabled == false
  tags: ['mpd']

- import_tasks: radiogagad.yml
  when: radiogagad_enabled == true
  tags: ['radiogagad']

- name: Copy playlists files
  template:
    src: playlist.m3u
    dest: "{{ mpd_rootdir }}/playlists/{{ item.file }}"
    owner: mpd
    group: audio
    mode: 0644
  loop: "{{ playlists }}"
  tags: ['playlists']

# LBU commit must always be the last
- import_tasks: lbu.yml
  tags: ['always']
