- name: Setting facts
  set_fact:
    hostname: "{{ hostname | default(ansible_hostname) }}"
    usbkey_enabled: "{{ usbkey_enabled | default(true) | bool }}"
    usbkey_label: "{{ usbkey_label | default('') }}"
    usbkey_mount_path: "{{ usbkey_mount_path | default('') }}"
  tags: ["always"]

- name: Enable community APK repository
  replace:
    path: /etc/apk/repositories
    regexp: '^#(http://.*/v.*/community)'
    replace: '\1'
  tags: ['base']

- name: Install base packages
  apk:
    name: "{{ item }}"
    state: present
  loop:
    - raspberrypi
    - f2fs-tools
  tags: ['base']

- name: Disable useless services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - "crond"
  tags: ['base']

- name: Remove useless console getty
  lineinfile:
    path: /etc/inittab
    state: absent
    regexp: '^{{ item }}:.*getty.*' 
  loop:
    - "tty2"
    - "tty3"
    - "tty4"
    - "tty5"
    - "tty6"
  tags: ['base']

- name: Blacklist video related modules
  lineinfile:
    path: /etc/modprobe.d/radiogaga_blacklist.conf
    line: "{{ item }}"
    create: yes
  loop:
    - blacklist bcm2835_codec
    - blacklist bcm2835_v4l2
    - blacklist media
    - blacklist vc_sm_cma
  tags: ['base']

- import_tasks: avahi.yml
  tags: ['base']

- import_tasks: rngd.yml
  tags: ['base']

- import_tasks: syslog.yml
  tags: ['base']

# - import_tasks: firmware.yml
#   tags: ['base']



# - name: Disable IPv4 DAD
#   file:
#     path: /etc/network/if-up.d/dad
#     mode: "a-x"
#   tags: ['base']

# - name: Add USB key in /etc/fstab
#   mount:
#     path: "{{ usbkey_mount_path }}"
#     src: "LABEL={{ usbkey_label }}"
#     fstype: f2fs
#     opts: noatime
#     passno: "2"
#     state: mounted





# - import_tasks: samba.yml
#   tags: ['samba']

# - import_tasks: mpd.yml
#   tags: ['mpd']

# - import_tasks: radiogagad.yml
#   tags: ['radiogagad']

# LBU commit must always be the last
- import_tasks: lbu.yml
  tags: ['always']
