- import_tasks: ssh.yml
  tags: ['never', 'ssh'] 

- name: Install Raspberry Pi support tools
  apk:
    name: raspberrypi
    state: present
  tags: ['base']

# use /opt/vc/bin/vcgencmd installed with raspberrypi package
- import_tasks: usbboot.yml
  tags: ['base']

- import_tasks: firmware.yml
  tags: ['base']

- name: Enable community APK repository
  replace:
    path: /etc/apk/repositories
    regexp: '^#(http://.*/v.*/community)'
    replace: '\1'
  tags: ['base']

- name: Install F2FS tools
  apk:
    name: f2fs-tools
    state: present
  tags: ['base']

- name: Blacklist useless kernel modules
  copy:
    src: radiogaga_blacklist.conf
    dest: /etc/modprobe.d/radiogaga_blacklist.conf
  tags: ['base']

- name: Disable useless services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - "crond"
  tags: ['base']

- name: Remove useless console getty
  lineinfile:
    path: /etc/inittab
    state: absent
    regexp: '^{{ item }}:.*getty.*' 
  loop:
    - "tty2"
    - "tty3"
    - "tty4"
    - "tty5"
    - "tty6"
  tags: ['base']

- name: Disable IPv4 DAD
  file:
    path: /etc/network/if-up.d/dad
    mode: "a-x"
  tags: ['base']

# https://bugs.alpinelinux.org/issues/8028
- name: Workaround for busybox syslogd -Z option broken
  replace:
    path: /etc/conf.d/syslog
    regexp: '^SYSLOGD_OPTS="(.*)-Z(.*)"'
    replace: 'SYSLOGD_OPTS="\1\2"'
  notify: restart syslogd
  tags: ['base']

- import_tasks: avahi.yml
  tags: ['base']

- import_tasks: rngd.yml
  tags: ['base']

- import_tasks: samba.yml
  tags: ['samba']

- import_tasks: mpd.yml
  tags: ['mpd']

- import_tasks: radiogagad.yml
  tags: ['radiogagad']

# LBU commit must always be the last
- import_tasks: lbu.yml
  tags: ['always']
