- name: Install mpd package
  apk:
    name: mpd
    state: present

- name: Enable mpd
  service:
    name: mpd
    enabled: yes
  notify: restart mpd

- name: Copy mpd.conf
  template:
    src: mpd.conf
    dest: /etc/mpd.conf
    owner: mpd
    group: audio
    mode: 0640
  notify: restart mpd

- name: Create a directory for mpd on USBKEY
  file:
    path: "{{ usbkey_mount_path }}/mpd"
    state: directory
    owner: mpd
    group: audio
    mode: 0755

- name: Create music & playlists directories
  file:
    path: "{{ item }}"
    state: directory
    owner: mpd
    group: audio
    mode: 0777
  with_items:
    - "{{ usbkey_mount_path }}/mpd/music"
    - "{{ usbkey_mount_path }}/mpd/playlists"

- name: Check if file mpd.db exists
  stat:
    path: "{{ usbkey_mount_path }}/mpd/mpd.db"
  register: mpddb

- name: Fix attributes on file mpd.db
  file:
    path: "{{ usbkey_mount_path }}/mpd/mpd.db"
    state: file
    owner: mpd
    group: audio
    mode: 0644
  when: mpddb.stat.exists == true