- name: Install mpd package
  apk:
    name: mpd
    state: present

- name: Enable mpd
  service:
    name: mpd
    enabled: yes
  notify: restart mpd

- name: Create directories for mpd on SD card
  file:
    path: "{{ item }}"
    state: directory
    owner: mpd
    group: audio
    mode: 0755
  loop:
    - "{{ mpd_rootdir }}"
    - "{{ mpd_rootdir }}/music"
    - "{{ mpd_rootdir }}/playlists"
  when: usbkey_enabled == false

- name: Copy /etc/mpd.conf
  template:
    src: mpd.conf
    dest: /etc/mpd.conf
    owner: mpd
    group: audio
    mode: 0640
  notify: restart mpd
