- name: Check current firmware configuration
  copy:
    src: usercfg.txt
    dest: /media/mmcblk0p1/usercfg.txt
  check_mode: true
  register: firmware

- name: Setup Firmware
  include_tasks: firmware.yml
  when: firmware.changed
