- name: Install Raspberry Pi support tools
  apk:
    name: raspberrypi
    state: present

- name: Check current firmware configuration
  copy:
    src: usercfg.txt
    dest: /media/mmcblk0p1/usercfg.txt
  check_mode: true
  register: firmware

- name: Setup Firmware
  include_tasks: firmware.yml
  when: firmware.changed

- name: Blacklist useless kernel modules
  copy:
    src: radiogaga_blacklist.conf
    dest: /etc/modprobe.d/radiogaga_blacklist.conf

- name: Disable useless services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - "crond"

- name: Remove useless console getty
  lineinfile:
    path: /etc/inittab
    state: absent
    regexp: '^{{ item }}:.*getty.*' 
  loop:
    - "tty2"
    - "tty3"
    - "tty4"
    - "tty5"
    - "tty6"

# https://bugs.alpinelinux.org/issues/8028
- name: Workaround for busybox syslogd -Z option broken
  replace:
    path: /etc/conf.d/syslog
    regexp: '^SYSLOGD_OPTS="(.*)-Z(.*)"'
    replace: 'SYSLOGD_OPTS="\1\2"'
  notify: restart syslogd
